//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sitecore.Modules.EventCalendar.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sitecore.Modules.EventCalendar.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find Event node with ID {0}.
        /// </summary>
        internal static string COULD_NOT_FIND_EVENT {
            get {
                return ResourceManager.GetString("COULD_NOT_FIND_EVENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar Demo Prototype.zip.
        /// </summary>
        internal static string DemoPackageName {
            get {
                return ResourceManager.GetString("DemoPackageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Developer Training.
        /// </summary>
        internal static string DveloperTitle0 {
            get {
                return ResourceManager.GetString("DveloperTitle0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Developer.
        /// </summary>
        internal static string DveloperTitle1 {
            get {
                return ResourceManager.GetString("DveloperTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Time must occur after Start Time!.
        /// </summary>
        internal static string END_AFTER_START {
            get {
                return ResourceManager.GetString("END_AFTER_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to College Student Seminar.
        /// </summary>
        internal static string EndUserTitle0 {
            get {
                return ResourceManager.GetString("EndUserTitle0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End User Training.
        /// </summary>
        internal static string EndUserTitle1 {
            get {
                return ResourceManager.GetString("EndUserTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator Training.
        /// </summary>
        internal static string EndUserTitle2 {
            get {
                return ResourceManager.GetString("EndUserTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the name of the new item:.
        /// </summary>
        internal static string ENTER_ITEM_NAME {
            get {
                return ResourceManager.GetString("ENTER_ITEM_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to install the Calendar demonstration items?.
        /// </summary>
        internal static string INSTALL_CALENDAR_DEMO_ITEMS {
            get {
                return ResourceManager.GetString("INSTALL_CALENDAR_DEMO_ITEMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item has no layout..
        /// </summary>
        internal static string ITEM_HAS_NO_LAYOUT {
            get {
                return ResourceManager.GetString("ITEM_HAS_NO_LAYOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Room 100.
        /// </summary>
        internal static string Location0 {
            get {
                return ResourceManager.GetString("Location0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Room 200.
        /// </summary>
        internal static string Location1 {
            get {
                return ResourceManager.GetString("Location1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Room 101.
        /// </summary>
        internal static string Location2 {
            get {
                return ResourceManager.GetString("Location2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Room 205.
        /// </summary>
        internal static string Location3 {
            get {
                return ResourceManager.GetString("Location3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Room 110.
        /// </summary>
        internal static string Location4 {
            get {
                return ResourceManager.GetString("Location4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brown Bag Lunch.
        /// </summary>
        internal static string Lunch0 {
            get {
                return ResourceManager.GetString("Lunch0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Official lunch.
        /// </summary>
        internal static string Lunch1 {
            get {
                return ResourceManager.GetString("Lunch1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power lunch.
        /// </summary>
        internal static string Lunch2 {
            get {
                return ResourceManager.GetString("Lunch2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We decided it was about time for a roadmap meeting so we came up with the idea of the Brown Bag Lunch. Bring your goodies in a brown bag (we have some downstairs in the kitchen for those that don&apos;t know what they are) and we will have an open meeting to
        ///discuss our future plans.  Partners and other interested parties are welcome..
        /// </summary>
        internal static string LunchDescription0 {
            get {
                return ResourceManager.GetString("LunchDescription0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let&apos;s do lunch! It is time for a more official meeting to discuss a few new strategies. So all employees are formally invited to attend the Official Lunch at the best restaurant in town (you all know it!) to give your personal input. It is all paid for so just bring a notebook and pen, and of course, yourself..
        /// </summary>
        internal static string LunchDescription1 {
            get {
                return ResourceManager.GetString("LunchDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are invited to join us for a quick Power Lunch.  This time we&apos;ll demonstrate the features of the newest release of our software.  Stop by and find out how you can save time and impress your boss!.
        /// </summary>
        internal static string LunchDescription2 {
            get {
                return ResourceManager.GetString("LunchDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13:30.
        /// </summary>
        internal static string LunchEndTime0 {
            get {
                return ResourceManager.GetString("LunchEndTime0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13:30.
        /// </summary>
        internal static string LunchEndTime1 {
            get {
                return ResourceManager.GetString("LunchEndTime1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 13:00.
        /// </summary>
        internal static string LunchEndTime2 {
            get {
                return ResourceManager.GetString("LunchEndTime2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Canteen.
        /// </summary>
        internal static string LunchLocation0 {
            get {
                return ResourceManager.GetString("LunchLocation0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Restaurant.
        /// </summary>
        internal static string LunchLocation1 {
            get {
                return ResourceManager.GetString("LunchLocation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Canteen.
        /// </summary>
        internal static string LunchLocation2 {
            get {
                return ResourceManager.GetString("LunchLocation2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday|2.
        /// </summary>
        internal static string LunchStartDate0 {
            get {
                return ResourceManager.GetString("LunchStartDate0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday|3.
        /// </summary>
        internal static string LunchStartDate1 {
            get {
                return ResourceManager.GetString("LunchStartDate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday|1.
        /// </summary>
        internal static string LunchStartDate2 {
            get {
                return ResourceManager.GetString("LunchStartDate2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12:00.
        /// </summary>
        internal static string LunchStartTime0 {
            get {
                return ResourceManager.GetString("LunchStartTime0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12:00.
        /// </summary>
        internal static string LunchStartTime1 {
            get {
                return ResourceManager.GetString("LunchStartTime1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12:00.
        /// </summary>
        internal static string LunchStartTime2 {
            get {
                return ResourceManager.GetString("LunchStartTime2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;$Input&apos; is not a valid name..
        /// </summary>
        internal static string NOT_VALIDE_NAME {
            get {
                return ResourceManager.GetString("NOT_VALIDE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent item not found..
        /// </summary>
        internal static string PARENT_NOT_FOUND {
            get {
                return ResourceManager.GetString("PARENT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theater Visit.
        /// </summary>
        internal static string Party0 {
            get {
                return ResourceManager.GetString("Party0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Football Fun Day.
        /// </summary>
        internal static string Party1 {
            get {
                return ResourceManager.GetString("Party1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After Football Dinner &amp; Drinks.
        /// </summary>
        internal static string Party2 {
            get {
                return ResourceManager.GetString("Party2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Office Party.
        /// </summary>
        internal static string Party3 {
            get {
                return ResourceManager.GetString("Party3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birthday Party.
        /// </summary>
        internal static string Party4 {
            get {
                return ResourceManager.GetString("Party4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exercise Walk.
        /// </summary>
        internal static string Party5 {
            get {
                return ResourceManager.GetString("Party5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Everyone is talking about the big show! Come with us to the local theatre and watch a great comedy with us. We got a great group rate, so contact Sally if you&apos;re interested.  We&apos;ve heard the show is funny and suitable for all ages, plus we will be going to the pub afterwards..
        /// </summary>
        internal static string PartyDescription0 {
            get {
                return ResourceManager.GetString("PartyDescription0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A traditional event where we meet up to play football. We usually play in the park by town center and there is always room for more, so bring your friends and have let&apos;s have fun!.
        /// </summary>
        internal static string PartyDescription1 {
            get {
                return ResourceManager.GetString("PartyDescription1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After a day of football, what could be better than meeting up for some burgers and drinks?  In fact, that sounds good even if you didn&apos;t spend the day playing football!  Join us either way..
        /// </summary>
        internal static string PartyDescription2 {
            get {
                return ResourceManager.GetString("PartyDescription2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This event is a must for all employees and open to all our partners!  If you&apos;re a partner, this is a great chance for your to meet in person the people you&apos;re only spoken with over the phone or via e-mail..
        /// </summary>
        internal static string PartyDescription3 {
            get {
                return ResourceManager.GetString("PartyDescription3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey guys, I turn 25 on Wednesday so cake and beer are on me!.
        /// </summary>
        internal static string PartyDescription4 {
            get {
                return ResourceManager.GetString("PartyDescription4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey, feeling a little overweight? Putting on too many kilograms sitting at the desk all day? Then join us for a great hike in the mountains. It&apos;s sure to trim you down and get you feeling healthy again!.
        /// </summary>
        internal static string PartyDescription5 {
            get {
                return ResourceManager.GetString("PartyDescription5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 23:30.
        /// </summary>
        internal static string PartyEndTime0 {
            get {
                return ResourceManager.GetString("PartyEndTime0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 17:00.
        /// </summary>
        internal static string PartyEndTime1 {
            get {
                return ResourceManager.GetString("PartyEndTime1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 22:00.
        /// </summary>
        internal static string PartyEndTime2 {
            get {
                return ResourceManager.GetString("PartyEndTime2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 22:00.
        /// </summary>
        internal static string PartyEndTime3 {
            get {
                return ResourceManager.GetString("PartyEndTime3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 17:00.
        /// </summary>
        internal static string PartyEndTime4 {
            get {
                return ResourceManager.GetString("PartyEndTime4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 22:00.
        /// </summary>
        internal static string PartyEndTime5 {
            get {
                return ResourceManager.GetString("PartyEndTime5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Theater.
        /// </summary>
        internal static string PartyLocation0 {
            get {
                return ResourceManager.GetString("PartyLocation0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Park.
        /// </summary>
        internal static string PartyLocation1 {
            get {
                return ResourceManager.GetString("PartyLocation1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Pub.
        /// </summary>
        internal static string PartyLocation2 {
            get {
                return ResourceManager.GetString("PartyLocation2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Canteen at our Offices.
        /// </summary>
        internal static string PartyLocation3 {
            get {
                return ResourceManager.GetString("PartyLocation3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Canteen.
        /// </summary>
        internal static string PartyLocation4 {
            get {
                return ResourceManager.GetString("PartyLocation4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our office parking lot.
        /// </summary>
        internal static string PartyLocation5 {
            get {
                return ResourceManager.GetString("PartyLocation5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday|1.
        /// </summary>
        internal static string PartyStartDate0 {
            get {
                return ResourceManager.GetString("PartyStartDate0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday|1.
        /// </summary>
        internal static string PartyStartDate1 {
            get {
                return ResourceManager.GetString("PartyStartDate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday|1.
        /// </summary>
        internal static string PartyStartDate2 {
            get {
                return ResourceManager.GetString("PartyStartDate2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday|2.
        /// </summary>
        internal static string PartyStartDate3 {
            get {
                return ResourceManager.GetString("PartyStartDate3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday|2.
        /// </summary>
        internal static string PartyStartDate4 {
            get {
                return ResourceManager.GetString("PartyStartDate4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday|2.
        /// </summary>
        internal static string PartyStartDate5 {
            get {
                return ResourceManager.GetString("PartyStartDate5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 19:00.
        /// </summary>
        internal static string PartyStartTime0 {
            get {
                return ResourceManager.GetString("PartyStartTime0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10:00.
        /// </summary>
        internal static string PartyStartTime1 {
            get {
                return ResourceManager.GetString("PartyStartTime1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18:00.
        /// </summary>
        internal static string PartyStartTime2 {
            get {
                return ResourceManager.GetString("PartyStartTime2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18:00.
        /// </summary>
        internal static string PartyStartTime3 {
            get {
                return ResourceManager.GetString("PartyStartTime3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16:00.
        /// </summary>
        internal static string PartyStartTime4 {
            get {
                return ResourceManager.GetString("PartyStartTime4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 08:00.
        /// </summary>
        internal static string PartyStartTime5 {
            get {
                return ResourceManager.GetString("PartyStartTime5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have removed all calendar controls except the HTMLHeader. This control is not required unless you select one or more additional controls.&lt;br/&gt;&lt;br/&gt;Do you want to remove this control as well?.
        /// </summary>
        internal static string REMOVE_ONE_HTMLHEADER {
            get {
                return ResourceManager.GetString("REMOVE_ONE_HTMLHEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar controls require specific statements in the HTML header. The HTMLHeader control generates these statements. Please select this control and specify a placeholder key that corresponds to a placeholder in the HTML header this item&apos;s associated layout..
        /// </summary>
        internal static string REQUIRES_HTMLHEADER {
            get {
                return ResourceManager.GetString("REQUIRES_HTMLHEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The event item \&quot;{0}\&quot; is based on the template \&quot;{1}\&quot; and not \&quot;{2}\&quot; as expected.
        /// </summary>
        internal static string UNSUPPORT_TEMPLATE {
            get {
                return ResourceManager.GetString("UNSUPPORT_TEMPLATE", resourceCulture);
            }
        }
    }
}
